Repository blazium-engine/blazium, pull requests merged in 2025-03, with the labels that each got.

#361 Modify web export to have all the JavaScript in a file
  misc/dist/html/engine-starter.js
  misc/dist/html/full-size.html
  misc/dist/html/third_party_services/discord-embed.js
  misc/dist/html/third_party_services/youtube-playables.js
  platform/web/emscripten_helpers.py
  platform/web/eslint.config.cjs
  platform/web/export/export_plugin.cpp
  platform/web/export/export_plugin.h
Labels: enhancement

#367 Fix Editor TopBar for RTL layout
  editor/editor_node.cpp
Labels: topic:editor, regression, bug

#375 Revert "Improve: prevent ProjectSettings from emitting settings chang…
  core/config/project_settings.cpp
Labels: topic:core, regression, bug

#371 Enable fast saving mode for PNGs
  core/io/image.cpp
  core/io/image.h
  doc/classes/Image.xml
  drivers/png/png_driver_common.cpp
Labels: documentation, enhancement, topic:core

#374 Center Editor Main Screen Buttons
  editor/editor_node.cpp
Labels: topic:editor

#380 Add API Type Override Method to `ClassDB` + `ClassDB` Binding Enhancements
  core/core_bind.cpp
  core/core_bind.h
  core/object/class_db.cpp
  core/object/class_db.h
  doc/classes/ClassDB.xml
Labels: documentation, enhancement, topic:core

#383 Fix for thread web export by separating the JS files
  misc/dist/html/full-size.html
  platform/web/export/export_plugin.cpp
  platform/web/export/export_plugin.h
Labels: bug

#388 Fix remove control from container in title bar using wrong parent.
  editor/plugins/editor_plugin.cpp
Labels: topic:editor, regression, bug

#387 Prevent tooltip from showing when hovering past end of script line
  scene/gui/code_edit.cpp
  scene/gui/text_edit.cpp
  scene/gui/text_edit.h
  tests/scene/test_text_edit.h
Labels: topic:gui, bug

#389 Revert "Made Node.find_children faster."
  scene/main/node.cpp
  scene/main/node.h
Labels: regression, bug

#390 Fix bug_report.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, bug

#391 Cherry-pick missing commits from 4.4 features
  doc/classes/JavaClassWrapper.xml
  editor/plugins/visual_shader_editor_plugin.cpp
  editor/plugins/visual_shader_editor_plugin.h
  modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs
  modules/mono/thirdparty/libSystem.Security.Cryptography.Native.Android.jar
  platform/android/api/api.cpp
  platform/android/api/java_class_wrapper.h
  platform/android/java/app/build.gradle
  platform/android/java_class_wrapper.cpp
Labels: documentation, topic:editor, cherry-pick

#392 fix bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: documentation, bug

#395 Remove dash from prerelease icon names [ci skip]
  misc/dist/icon_generation/icon_badges/status_prerelease.svg
  misc/dist/icon_generation/icon_badges/status_prerelease_mini.svg
  misc/scripts/make_icons.py
  platform/android/icons/prerelease/mipmap-hdpi/icon.png
  platform/android/icons/prerelease/mipmap-hdpi/icon_background.png
  platform/android/icons/prerelease/mipmap-hdpi/icon_foreground.png
  platform/android/icons/prerelease/mipmap-hdpi/icon_monochrome.png
  platform/android/icons/prerelease/mipmap-mdpi/icon.png
  platform/android/icons/prerelease/mipmap-mdpi/icon_background.png
  platform/android/icons/prerelease/mipmap-mdpi/icon_foreground.png
  platform/android/icons/prerelease/mipmap-mdpi/icon_monochrome.png
  platform/android/icons/prerelease/mipmap-xhdpi/icon.png
  platform/android/icons/prerelease/mipmap-xhdpi/icon_background.png
  platform/android/icons/prerelease/mipmap-xhdpi/icon_foreground.png
  platform/android/icons/prerelease/mipmap-xhdpi/icon_monochrome.png
  platform/android/icons/prerelease/mipmap-xxhdpi/icon.png
  platform/android/icons/prerelease/mipmap-xxhdpi/icon_background.png
  platform/android/icons/prerelease/mipmap-xxhdpi/icon_foreground.png
  platform/android/icons/prerelease/mipmap-xxhdpi/icon_monochrome.png
  platform/android/icons/prerelease/mipmap-xxxhdpi/icon.png
  platform/android/icons/prerelease/mipmap-xxxhdpi/icon_background.png
  platform/android/icons/prerelease/mipmap-xxxhdpi/icon_foreground.png
  platform/android/icons/prerelease/mipmap-xxxhdpi/icon_monochrome.png
  platform/android/icons/prerelease/mipmap/icon.png
  platform/android/icons/prerelease/mipmap/icon_background.png
  platform/android/icons/prerelease/mipmap/icon_foreground.png
  platform/android/icons/prerelease/mipmap/icon_monochrome.png
  platform/linuxbsd/icons/blazium_prerelease.svg
  platform/linuxbsd/icons/blazium_prerelease_128px.png
  platform/linuxbsd/icons/blazium_prerelease_16px.png
  platform/linuxbsd/icons/blazium_prerelease_192px.png
  platform/linuxbsd/icons/blazium_prerelease_22px.png
  platform/linuxbsd/icons/blazium_prerelease_24px.png
  platform/linuxbsd/icons/blazium_prerelease_256px.png
  platform/linuxbsd/icons/blazium_prerelease_32px.png
  platform/linuxbsd/icons/blazium_prerelease_48px.png
  platform/linuxbsd/icons/blazium_prerelease_64px.png
  platform/linuxbsd/icons/blazium_prerelease_96px.png
  platform/macos/icons/Blazium_prerelease.icns
  platform/windows/icons/blazium_console_prerelease.ico
  platform/windows/icons/blazium_prerelease.ico
Labels: cicd, bug

#394 Fix MarginContainer padding regression.
  doc/classes/MarginContainer.xml
  scene/theme/blazium_default_theme.cpp
Labels: topic:gui, regression

#397 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_proposal.yml
Labels: documentation, enhancement

#399 Made Node.find_children faster take 4.
  scene/main/node.cpp
  scene/main/node.h
Labels: enhancement

#402 GDScript bug fixes batch.
  core/doc_data.cpp
  core/extension/extension_api_dump.cpp
  core/object/class_db.cpp
  core/object/method_bind.h
  core/object/object.cpp
  core/object/object.h
  editor/animation_track_editor.cpp
  editor/connections_dialog.cpp
  editor/doc_tools.cpp
  editor/property_selector.cpp
  modules/fbx/register_types.cpp
  modules/gdscript/gdscript_analyzer.cpp
  modules/gdscript/gdscript_compiler.cpp
  modules/gdscript/gdscript_editor.cpp
  modules/gdscript/gdscript_parser.cpp
  modules/gdscript/gdscript_parser.h
  modules/gdscript/gdscript_utility_functions.cpp
  modules/gdscript/register_types.cpp
  modules/gdscript/tests/gdscript_test_runner_suite.h
  modules/gdscript/tests/scripts/completion/common/invalid_super_call_1.cfg
  modules/gdscript/tests/scripts/completion/common/invalid_super_call_1.gd
  modules/gdscript/tests/scripts/completion/common/invalid_super_call_2.cfg
  modules/gdscript/tests/scripts/completion/common/invalid_super_call_2.gd
  modules/gltf/register_types.cpp
  modules/minimp3/register_types.cpp
  modules/mono/editor/bindings_generator.cpp
  modules/openxr/register_types.cpp
  modules/vorbis/register_types.cpp
  scene/main/node.cpp
  tests/core/object/test_class_db.h
Labels: bug, GDScript

#403 Update: Add space_step() to step physics simulation manually
  modules/godot_physics_2d/godot_physics_server_2d.cpp
  modules/godot_physics_3d/godot_physics_server_3d.cpp
  modules/jolt_physics/jolt_physics_server_3d.cpp
  modules/jolt_physics/jolt_physics_server_3d.h
Labels: enhancement, cherry-pick

#404 Fix android exports crash after JavaClassWrapper changes
  platform/android/java_class_wrapper.cpp
  platform/android/jni_utils.cpp
Labels: regression, bug

#408 Drop files as UID
  doc/classes/EditorSettings.xml
  editor/editor_property_name_processor.cpp
  editor/editor_settings.cpp
  editor/plugins/script_text_editor.cpp
Labels: documentation, enhancement, topic:editor, cherry-pick
