Repository blazium-engine/blazium, pull requests merged in 2025-05, with the labels that each got.

#468 Fix `EventListenerLineEdit` ignores the first input.
  editor/event_listener_line_edit.cpp
  editor/input_event_configuration_dialog.cpp
Labels: topic:editor, regression, bug

#469 Fix CheckBox icon modulates over blazium theme generated colors.
  editor/themes/editor_theme_manager.cpp
  scene/theme/icons/checked.svg
  scene/theme/icons/checked_disabled.svg
  scene/theme/icons/unchecked.svg
  scene/theme/icons/unchecked_disabled.svg
Labels: topic:gui, regression, bug

#489 Fix Vulkan SDK setup for MacOS
  misc/scripts/install_vulkan_sdk_macos.sh
Labels: bug, cherry-pick
